(char*) "at_time", (char*) "", (char*) "ms", 0,
(char*) "state_discontinuity", (char*) "", (char*) "m9", (char*) "m9", 0,
(char*) "net_send", (char*) "", (char*) "ms", (char*) "m9", 0,
(char*) "net_event", (char*) "", (char*) "ms", 0,
(char*) "net_move", (char*) "", (char*) "ms", 0,
(char*) "nrn_ghk", (char*) "millicoulombs/cm3", (char*) "millivolt", (char*) "milli/liter", (char*) "milli/liter", (char*) "", 0,
